version: "3.9"

services:
  api-with-air:
    # image: cosmtrek/air
    build:
      context: .
      dockerfile: DockerfileAir
    working_dir: /app
    ports:
      - "8000:8000"
    volumes:
      - ./.:/app
    environment:
      - COURSEAPI_HOST=http://host.docker.internal:3169
